# Generated by Django 5.0.6 on 2024-05-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='restaurant_menu\\static\\images\\'),
        ),
    ]
